on:
  push:
#    tags:
#      - 'testprefix*' 

name: testTriggerRelease

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: echo 'foo' > bar
      - run: git config --global user.email "github-actions@github.com"
      - run: git config --global user.name "RobotBobert"
      - run: git add -A
      - run: git commit -m "baz"
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bar
          asset_name: bar
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"
